[info]
file = "Info.txt"

[temporal]
file = "Temporal Distance.txt"

[gps]
file = "MAP.txt"

[[kinematics]]
name = "Ankle Dorsiflexion"
left_file = "Left Ankle Angles.txt"
right_file = "Right Ankle Angles.txt"
norm_file = "Norm Ankle Angles X.txt"
y_axis = [-30, 30]

[[kinematics]]
name = "Ankle Inversion"
left_file = "Left Ankle Inversion.txt"
right_file = "Right Ankle Inversion.txt"
norm_file = "Norm Ankle Angles Y.txt"
y_axis = [-20, 20]

[[kinematics]]
name = "Ankle Rotation"
left_file = "Left Ankle Rotation.txt"
right_file = "Right Ankle Rotation.txt"
norm_file = "Norm Ankle Angles Z.txt"
y_axis = [-30, 30]

[[kinematics]]
name = "Foot Pitch"
left_file = "Left Foot Pitch Angles.txt"
right_file = "Right Foot Pitch Angles.txt"
norm_file = "Norm Foot Pitch.txt"
y_axis = [-90, 30]

[[kinematics]]
name = "Foot Internal Progression"
left_file = "Left Foot Progression.txt"
right_file = "Right Foot Progression.txt"
norm_file = "Norm Foot Progression.txt"
y_axis = [-45, 15]

[[kinematics]]
name = "Knee Flexion"
left_file = "Left Knee Angles.txt"
right_file = "Right Knee Angles.txt"
norm_file = "Norm Knee Angles X.txt"
y_axis = [-15, 75]

[[kinematics]]
name = "Knee Varus"
left_file = "Left Knee Adduction.txt"
right_file = "Right Knee Adduction.txt"
norm_file = "Norm Knee Angles Y.txt"
y_axis = [-20, 20]

[[kinematics]]
name = "Knee Internal Rotation"
left_file = "Left Knee Rotation.txt"
right_file = "Right Knee Rotation.txt"
norm_file = "Norm Knee Angles Z.txt"
y_axis = [-50, 10]

[[kinematics]]
name = "Hip Flexion"
left_file = "Left Hip Angles.txt"
right_file = "Right Hip Angles.txt"
norm_file = "Norm Hip Angles X.txt"
y_axis = [-30, 60]

[[kinematics]]
name = "Hip Adduction"
left_file = "Left Hip Adduction.txt"
right_file = "Right Hip Adduction.txt"
norm_file = "Norm Hip Angles Y.txt"
y_axis = [-20, 20]

[[kinematics]]
name = "Hip Internal Rotation"
left_file = "Left Hip Rotation.txt"
right_file = "Right Hip Rotation.txt"
norm_file = "Norm Hip Angles Z.txt"
y_axis = [-30, 30]

[[kinematics]]
name = "Pelvic Anterior Tilt"
left_file = "Left Pelvic Tilt.txt"
right_file = "Right Pelvic Tilt.txt"
norm_file = "Norm Pelvic Angles X.txt"
y_axis = [-10, 20]

[[kinematics]]
name = "Pelvic Up Obliquity"
left_file = "Left Pelvic Obliquity.txt"
right_file = "Right Pelvic Obliquity.txt"
norm_file = "Norm Pelvic Angles Y.txt"
y_axis = [-15, 15]

[[kinematics]]
name = "Pelvic Internal Rotation"
left_file = "Left Pelvic Rotation.txt"
right_file = "Right Pelvic Rotation.txt"
norm_file = "Norm Pelvic Angles Z.txt"
y_axis = [-15, 15]

[[kinetics]]
name = "Hip Extensor Moment"
left_file = "Left Hip Extensor Moment.txt"
right_file = "Right Hip Extensor Moment.txt"
norm_file = "Norm Hip Moment X.txt"
y_axis = [-1.5, 1.5]
y_label = "Moment, Nm/kg"

[[kinetics]]
name = "Hip Valgus Moment"
left_file = "Left Hip Valgus Moment.txt"
right_file = "Right Hip Valgus Moment.txt"
norm_file = "Norm Hip Moment Y.txt"
y_axis = [-0.5, 1.2]
y_label = "Moment, Nm/kg"

[[kinetics]]
name = "Knee Extensor Moment"
left_file = "Left Knee Extensor Moment.txt"
right_file = "Right Knee Extensor Moment.txt"
norm_file = "Norm Knee Moment X.txt"
y_axis = [-1.0, 1.0]
y_label = "Moment, Nm/kg"

[[kinetics]]
name = "Knee Valgus Moment"
left_file = "Left Knee Valgus Moment.txt"
right_file = "Right Knee Valgus Moment.txt"
norm_file = "Norm Knee Moment Y.txt"
y_axis = [-0.4, 0.8]
y_label = "Moment, Nm/kg"

[[kinetics]]
name = "Ankle Plantarflexor Moment"
left_file = "Left Ankle Plantarflexor Moment.txt"
right_file = "Right Ankle Plantarflexor Moment.txt"
norm_file = "Norm Ankle Moment X.txt"
y_axis = [-0.5, 2.0]
y_label = "Moment, Nm/kg"

[[kinetics]]
name = "Ankle Eversion Moment"
left_file = "Left Ankle Eversion Moment.txt"
right_file = "Right Ankle Eversion Moment.txt"
norm_file = "Norm Ankle Moment Y.txt"
y_axis = [-0.3, 0.6]
y_label = "Moment, Nm/kg"

[[kinetics]]
name = "Hip Sagittal Power Generation"
left_file = "Left Hip Sagittal Power Generation.txt"
right_file = "Right Hip Sagittal Power Generation.txt"
norm_file = "Norm Hip Power Generation X.txt"
y_axis = [-2, 2]
y_label = "Power, W/kg"

[[kinetics]]
name = "Hip Frontal Power Generation"
left_file = "Left Hip Frontal Power Generation.txt"
right_file = "Right Hip Frontal Power Generation.txt"
norm_file = "Norm Hip Power Generation Y.txt"
y_axis = [-1, 1]
y_label = "Power, W/kg"

[[kinetics]]
name = "Knee Sagittal Power Generation"
left_file = "Left Knee Sagittal Power Generation.txt"
right_file = "Right Knee Sagittal Power Generation.txt"
norm_file = "Norm Knee Power Generation X.txt"
y_axis = [-2, 2]
y_label = "Power, W/kg"

[[kinetics]]
name = "Knee Frontal Power Generation"
left_file = "Left Knee Frontal Power Generation.txt"
right_file = "Right Knee Frontal Power Generation.txt"
norm_file = "Norm Knee Power Generation Y.txt"
y_axis = [-1, 1]
y_label = "Power, W/kg"

[[kinetics]]
name = "Ankle Sagittal Power Generation"
left_file = "Left Ankle Sagittal Power Generation.txt"
right_file = "Right Ankle Sagittal Power Generation.txt"
norm_file = "Norm Ankle Power Generation X.txt"
y_axis = [-1, 5]
y_label = "Power, W/kg"

[[kinetics]]
name = "Ankle Frontal Power Generation"
left_file = "Left Ankle Frontal Power Generation.txt"
right_file = "Right Ankle Frontal Power Generation.txt"
norm_file = "Norm Ankle Power Generation Y.txt"
y_axis = [-1, 1]
y_label = "Power, W/kg"

[[kinetics]]
name = "Anterior GRF"
left_file = "Left Anterior GRF.txt"
right_file = "Right Anterior GRF.txt"
norm_file = "Norm GRF X.txt"
y_axis = [-0.3, 0.3]
y_label = "Force, N/BW"
x_label = "Stance phase, %"

[[kinetics]]
name = "Medial GRF"
left_file = "Left Medial GRF.txt"
right_file = "Right Medial GRF.txt"
norm_file = "Norm GRF Y.txt"
y_axis = [-0.1, 0.1]
y_label = "Force, N/BW"
x_label = "Stance phase, %"

[[kinetics]]
name = "Vertical GRF"
left_file = "Left Vertical GRF.txt"
right_file = "Right Vertical GRF.txt"
norm_file = "Norm GRF Z.txt"
y_axis = [-0.1, 2.0]
y_label = "Force, N/BW"
x_label = "Stance phase, %"

[standard]
layout_kinematics = [
    ["Pelvic Anterior Tilt", "Pelvic Up Obliquity", "Pelvic Internal Rotation"],
    ["Hip Flexion", "Hip Adduction", "Hip Internal Rotation"],
    ["Knee Flexion", "Knee Varus", "Knee Internal Rotation"],
    ["Ankle Dorsiflexion", "Ankle Inversion", "Ankle Rotation"],
    ["Foot Pitch", "", "Foot Internal Progression"]
]
layout_kinetics = [
    ["Hip Extensor Moment", "Hip Valgus Moment", ""],
    ["Knee Extensor Moment", "Knee Valgus Moment", ""],
    ["Ankle Plantarflexor Moment", "Ankle Eversion Moment", ""],
    ["Hip Sagittal Power Generation", "Hip Frontal Power Generation", ""],
    ["Knee Sagittal Power Generation", "Knee Frontal Power Generation", ""],
    ["Ankle Sagittal Power Generation", "Ankle Frontal Power Generation", ""],
    ["Anterior GRF", "Medial GRF", "Vertical GRF"]
]

[colors]
left = "red"
right = "blue"
mean = "black"
static = "orange"

[size]
height = 600
width = 1100
small_height = 275
small_width = 400

[phases]
# names = [
#     "Full Cycle",
#     "Stance Phase", 
#     "Initial Contact", 
#     "Loading Response", 
#     "Midstance", 
#     "Terminal Stance", 
#     "Pre-swing", 
#     "Swing Phase",
#     "Initial Swing", 
#     "Midswing", 
#     "Terminal Swing"]
# ranges = [[0, 100], [0, 60], [0, 2], [2, 10], [10, 30], [30, 50], [50, 60], [60, 100], [60, 73], [73, 87], [87, 100]]
names = [
    "Loading Response",     
    "Stance Phase", 
    "Swing Phase",
    "Full Cycle"
]
ranges = [[0, 10], [0, 60], [60, 100], [0, 100]]
