[[kinematics]]
name = "Ankle Dorsiflexion"
left_file = "Left Ankle Angles.txt"
right_file = "Right Ankle Angles.txt"

[[kinematics]]
name = "Ankle Inversion"
left_file = "Left Ankle Inversion.txt"
right_file = "Right Ankle Inversion.txt"

[[kinematics]]
name = "Ankle Rotation"
left_file = "Left Ankle Rotation.txt"
right_file = "Right Ankle Rotation.txt"

[[kinematics]]
name = "Foot Pitch"
left_file = "Left Foot Pitch Angles.txt"
right_file = "Right Foot Pitch Angles.txt"

[[kinematics]]
name = "Foot Internal Progression"
left_file = "Left Foot Progression.txt"
right_file = "Right Foot Progression.txt"

[[kinematics]]
name = "Knee Flexion"
left_file = "Left Knee Angles.txt"
right_file = "Right Knee Angles.txt"

[[kinematics]]
name = "Knee Varus"
left_file = "Left Knee Adduction.txt"
right_file = "Right Knee Adduction.txt"

[[kinematics]]
name = "Knee Internal Rotation"
left_file = "Left Knee Rotation.txt"
right_file = "Right Knee Rotation.txt"

[[kinematics]]
name = "Hip Flexion"
left_file = "Left Hip Angles.txt"
right_file = "Right Hip Angles.txt"

[[kinematics]]
name = "Hip Adduction"
left_file = "Left Hip Adduction.txt"
right_file = "Right Hip Adduction.txt"

[[kinematics]]
name = "Hip Internal Rotation"
left_file = "Left Hip Rotation.txt"
right_file = "Right Hip Rotation.txt"

[[kinematics]]
name = "Pelvic Anterior Tilt"
left_file = "Left Pelvic Tilt.txt"
right_file = "Right Pelvic Tilt.txt"

[[kinematics]]
name = "Pelvic Up Obliquity"
left_file = "Left Pelvic Obliquity.txt"
right_file = "Right Pelvic Obliquity.txt"

[[kinematics]]
name = "Pelvic Internal Rotation"
left_file = "Left Pelvic Rotation.txt"
right_file = "Right Pelvic Rotation.txt"

#[[kinetics]]
#name = "Anterior GRF"
#left_file = "Left GRF X.txt"
#right_file = "Right GRF X.txt"

#[[kinetics]]
#name = "Medial GRF"
#left_file = "Left GRF Y.txt"
#right_file = "Right GRF Y.txt"

#[[kinetics]]
#name = "Vertical GRF"
#left_file = "Left GRF Z.txt"
#right_file = "Right GRF Z.txt"

[standard]
layout = [
    ["Pelvic Anterior Tilt", "Pelvic Up Obliquity", "Pelvic Internal Rotation"],
    ["Hip Flexion", "Hip Adduction", "Hip Internal Rotation"],
    ["Knee Flexion", "Knee Varus", "Knee Internal Rotation"],
    ["Ankle Dorsiflexion", "Ankle Inversion", "Ankle Rotation"],
    ["Foot Pitch", "", "Foot Internal Progression"]
]

[colors]
static = "orange"
mean = "black"
color_list = [
    "red",
    "blue",
    "green",
    "cyan",
    "magenta",
    "lime",
    "gray",
    "navy",
    "teal",
    "olive",
    "purple",
    "maroon",
    "aqua",
    "fuchsia",
    "silver",
    "blueviolet",
    "brown",
    "darkorange",
    "lightseagreen",
    "deeppink"
]

[size]
height = 500
width = 1000
