name: Auto assign to new issue
on:
  issues:
    types: [opened]
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
    - name: Assign to new issue
      uses: actions/github-script@v7
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.addAssignees({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            assignees: ['ilya112358']
          })
